title: "GenerativeAI Prompt Sample Japanese"
description: "GenerativeAI の Prompt のサンプル集"
baseurl: ""
url: ""
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
